from playwright.sync_api import Page

from Automation.utils import constants, data, local_data
from Automation.test_data import patient_data

class ReferralPage:
    def __init__(self, page:Page):
        self.page = page
        self.collaboration_tab = page.get_by_role("tab", name="Collaboration")
        self.referral_link = page.get_by_text("Referral")
        self.referral_out_tab = page.get_by_role("tab", name="Referral Out")
        self.referral_in_tab = page.get_by_role("tab", name="Referral In")
        self.search_input = page.get_by_placeholder("Search")
        self.add_referral_button = page.get_by_role("button", name="Add Referral")
        self.search_patient_input = page.get_by_placeholder("Search Patient")
        self.search_referral_from_input = page.get_by_placeholder("Search Referral From")
        self.referral_to_label = page.get_by_label("Referral To *")
        self.referral_speciality_label = page.locator("//p[text()='Referral Speciality']/following::input[@placeholder='Select Speciality']")
        self.choose_date_placeholder = page.get_by_placeholder("Choose Date")
        self.select_placeholder = page.get_by_placeholder("Select", exact=True)
        self.referral_reason_placeholder = page.get_by_placeholder("Referral Reason")
        self.referral_note_placeholder = page.get_by_placeholder("Referral Note")
        self.search_diagnosis_placeholder = page.get_by_placeholder("Search & Select Diagnosis Code")
        self.search_insurance_placeholder = page.get_by_placeholder("Search & Select Insurance")
        self.upload_file_button = page.get_by_role("button", name="Upload file")
        self.save_button = page.get_by_role("button", name="Save")
        self.add_person_icon = page.get_by_test_id("PersonAddIcon")
        
        self.fname = page.get_by_placeholder("Enter First Name")
        self.lname = page.get_by_placeholder("Enter Last Name")
        self.dob = page.get_by_placeholder("MM/DD/YYYY")
        self.gender = page.locator("input[name='gender']")
        self.email = page.get_by_placeholder("Enter Email")
        self.mobile = page.get_by_placeholder("Enter Mobile Number")
        self.add_btn = page.get_by_role("button", name="Add")
        self.patient_success_msg = page.get_by_text("Patient Details Added Successfully.")
        self.close_btn = page.get_by_title("Close")

    def navigate_to_referral(self):
        self.collaboration_tab.click()
        self.referral_link.click()
        
    def add_referral_out(self, referral_out_data: dict):
        self.referral_out_tab.click()
        self.add_referral_button.click()
        self.search_patient_input.fill(f"{referral_out_data['patient_name']}")
        self.page.get_by_role("option", name=f"{referral_out_data['patient_name']}").click()
        self.search_referral_from_input.click()
        self.page.get_by_role("option", name=local_data.provider1).click()
        self.referral_to_label.fill(local_data.referral_provider)
        self.page.get_by_role("option", name=local_data.referral_provider).click()
        self.referral_speciality_label.click()
        self.page.get_by_role("option", name=constants.speciality[2]).click()
        self.choose_date_placeholder.fill(data.today_date)
        self.select_placeholder.click()
        self.page.get_by_role("option", name=referral_out_data['priority']).click()
        self.referral_reason_placeholder.fill(referral_out_data['referall_reason'])
        self.referral_note_placeholder.fill(referral_out_data['referall_note'])
        self.search_diagnosis_placeholder.fill(referral_out_data['diagnosis_code'][0])
        self.page.get_by_text(referral_out_data['diagnosis_code'][1]).click()
        self.search_insurance_placeholder.click()
        self.page.set_input_files('input[type="file"]', './Automation/utils/uploads/test.pdf')
        self.save_button.click()
    
    def referral_out_list(self, patient: dict, referral_out_data: dict):
        self.page.get_by_placeholder("Search", exact=True).fill(referral_out_data['patient_name'])
        self.page.wait_for_timeout(1000)
        self.page.get_by_text(referral_out_data['patient_name']).click()
        self.page.get_by_text(patient.get("patient_mob_num")).click()
        if self.page.locator(f"span[aria-label='{patient.get('patient_email')}']").is_visible():
            self.page.locator(f"span[aria-label='{patient.get('patient_email')}']").hover()
            self.page.get_by_text(patient.get("patient_email")).click()
        else:
            self.page.locator(f"//span[text()='{patient.get('patient_email')}']").click()
        self.page.get_by_text(local_data.provider1).click()
        # self.page.get_by_text("(472) 584-5656").click()
        self.page.get_by_text(local_data.referral_provider).click()
        self.page.get_by_text(data.formatted_date).click()
        self.page.get_by_text(referral_out_data['priority']).click()
        self.page.get_by_text(referral_out_data['referall_reason']).click()
        self.page.get_by_test_id("MoreVertIcon").click()
        self.page.get_by_role("menuitem", name="View").click()
        self.page.wait_for_timeout(500)
        self.page.get_by_text("Response Summary").click()
        self.page.get_by_title("Response Summary").get_by_text(referral_out_data['patient_name']).click()
        self.page.get_by_text(patient['patient_dob'][1]).click()
        self.page.get_by_text(patient['patient_gender'], exact=True).click()
        self.page.get_by_title("Response Summary").get_by_text(local_data.provider1).click()
        # self.page.get_by_text("Neurology, Oncology").click()
        # self.page.get_by_title("Response Summary").get_by_text("(472) 584-5656").click()
        # self.page.get_by_text("45245").click()
        self.page.get_by_title("Response Summary").get_by_text(local_data.referral_provider).click()
        self.page.locator(f"//h4[text()='Response Date']/following::p[text()='{data.dt_format(data.current_date, '/')}']").click()
        self.page.locator(f"//h4[text()='Response Note']/following::p[text()='{referral_out_data['referall_note']}']").click()
        self.page.get_by_role("heading", name="Response Summary").get_by_test_id("CloseIcon").click()
        
    def referral_out_edit(self):
        self.page.get_by_test_id("MoreVertIcon").click()
        self.page.get_by_role("menuitem", name="Edit").click()
        self.page.get_by_text("Update Referral").click()
        self.page.get_by_test_id("CloseIcon").click()

    def referral_in_add_patient(self,patient: dict):
        self.referral_in_tab.click()
        self.add_referral_button.click()
        self.add_person_icon.first.click()
        self.fname.fill(patient['patient_fname'])
        self.lname.fill(patient['patient_lname'])
        self.dob.fill(patient['patient_dob'][0])
        self.gender.click()
        self.page.get_by_role("option", name="Male", exact=True).click()
        self.email.fill(patient['patient_email'])
        self.mobile.type(patient['patient_mob'])
        self.add_btn.click()
        self.patient_success_msg.click()
        self.close_btn.click()
        
    def add_referral_in(self, patient: dict, referral_in_data: dict):
        self.search_patient_input.click()
        self.search_patient_input.fill(f"{patient['patient_fname']} {patient['patient_lname']}")
        self.page.get_by_role("option", name=f"{patient['patient_fname']} {patient['patient_lname']}").click()
        self.search_referral_from_input.click()
        self.page.get_by_role("option", name=local_data.referral_provider).click()
        self.referral_to_label.fill(local_data.provider1)
        self.page.get_by_role("option", name=local_data.provider1).click()
        self.referral_speciality_label.click()
        self.page.get_by_role("option", name=constants.speciality[2]).click()
        self.choose_date_placeholder.fill(data.today_date)
        self.select_placeholder.click()
        self.page.get_by_role("option", name=referral_in_data['priority']).click()
        self.referral_reason_placeholder.fill(referral_in_data['referall_reason'])
        self.referral_note_placeholder.fill(referral_in_data['referall_note'])
        self.search_diagnosis_placeholder.fill(referral_in_data['diagnosis_code'][0])
        self.page.get_by_text(referral_in_data['diagnosis_code'][1]).click()
        self.search_insurance_placeholder.click()
        self.page.set_input_files('input[type="file"]', './Automation/utils/uploads/test.pdf')
        self.save_button.click()
        
    def referral_in_list(self, patient: dict, referral_in_data: dict):
        self.page.get_by_placeholder("Search", exact=True).fill(f"{patient['patient_fname']} {patient['patient_lname']}")
        self.page.wait_for_timeout(1000)
        self.page.get_by_text(f"{patient['patient_fname']} {patient['patient_lname']}").click()
        self.page.get_by_text(patient.get("patient_mob")).click()
        if self.page.locator(f"span[aria-label='{patient['patient_email']}']").is_visible():
            self.page.locator(f"span[aria-label='{patient['patient_email']}']").hover()
            self.page.get_by_text(patient['patient_email']).click()
        else:
            self.page.locator(f"//span[text()='{patient['patient_email']}']").click()
        self.page.get_by_text(local_data.referral_provider).click()
        self.page.get_by_text(local_data.provider1).click()
        # self.page.get_by_text("(472) 584-5656").click()
        self.page.get_by_text(data.formatted_date).click()
        self.page.get_by_text(referral_in_data['priority']).click()
        self.page.get_by_text(referral_in_data['referall_reason']).click()
        self.page.get_by_test_id("MoreVertIcon").click()
        self.page.get_by_role("menuitem", name="View").click()
        self.page.wait_for_timeout(1000)
        self.page.get_by_text("Response Summary").click()
        # Patient
        self.page.get_by_title("Response Summary").get_by_text(f"{patient['patient_fname']} {patient['patient_lname']}").click()
        self.page.get_by_text(patient['patient_dob'][1]).click()
        self.page.get_by_text(patient['patient_gender'], exact=True).click()
        # Response From
        self.page.get_by_title("Response Summary").get_by_text(local_data.referral_provider).click()
        # Response To
        self.page.get_by_title("Response Summary").get_by_text(local_data.provider1).click()
        # self.page.get_by_text("Neurology, Oncology").click()
        # self.page.get_by_title("Response Summary").get_by_text("(472) 584-5656").click()
        # self.page.get_by_text("45245").click()
        self.page.locator(f"//h4[text()='Response Date']/following::p[text()='{data.dt_format(data.current_date, '/')}']").click()
        self.page.locator(f"//h4[text()='Response Note']/following::p[text()='{referral_in_data['referall_note']}']").click()
        self.page.get_by_role("heading", name="Response Summary").get_by_test_id("CloseIcon").click()
