from playwright.sync_api import Page
from Automation.utils import creds, local_data

def medication(page: Page, medication: dict):
# MEDICATION
    page.get_by_role("tab", name="Medications").click()
    # Add Medication
    page.get_by_role("button", name="Add Medication").click()
    page.get_by_placeholder("Select Or Search Medicine").click()
    page.get_by_role("option", name=medication["medicine1"]).click()
    page.get_by_placeholder("Enter Quantity").fill("100")
    page.get_by_placeholder("Dosage Unit").click()
    page.get_by_role("option", name="Tablet (s)", exact=True).click()
    page.get_by_placeholder("frequency").click()
    page.get_by_role("option", name="Every Day").click()
    page.get_by_placeholder("When").click()
    page.get_by_role("option", name="Before Meal").click()
    page.get_by_placeholder("Time").click()
    page.get_by_role("option", name="Oral").click()
    page.locator("//input[@name='medicationStartDate']").click()
    page.locator("//input[@name='medicationStartDate']").fill("07-28-2024")
    page.locator("(//input[@placeholder='Choose Date'])[2]").click()
    page.locator("(//input[@placeholder='Choose Date'])[2]").fill("11-20-2024")
    page.get_by_placeholder("Select Provider").click()
    page.get_by_placeholder("Select Provider").fill(local_data.provider1)
    page.get_by_role("option", name=local_data.provider1).click()
    page.get_by_placeholder("Type here").click()
    page.get_by_placeholder("Type here").fill(medication["medication_note1"])
    page.get_by_role("button", name="Save").click()
    page.get_by_text("Medication created successfully").click()

    page.get_by_role("tab", name="Past Medications History").click()
    page.get_by_text(medication["medicine1"], exact=True).click()
    page.get_by_text("100 Tablet (s) Oral").click()
    page.get_by_test_id("MoreVertIcon").click()
    
    # Edit
    page.get_by_role("menuitem", name="Edit").click()
    page.get_by_role("heading", name="Edit Medication").click()
    page.get_by_placeholder("Select Or Search Medicine").click()
    page.get_by_placeholder("Select Or Search Medicine").press("Backspace")
    page.get_by_role("option", name=medication["medicine2"]).click()
    page.get_by_placeholder("Enter Quantity").fill("310")
    page.get_by_placeholder("Dosage Unit").click()
    page.get_by_role("option", name="Drops", exact=True).click()
    page.get_by_placeholder("frequency").click()
    page.get_by_role("option", name="Twice A Day").click()
    page.get_by_placeholder("When").click()
    page.get_by_role("option", name="Bedtime").click()
    page.get_by_placeholder("Time").click()
    page.get_by_role("option", name="Optic").click()
    page.locator("//input[@name='medicationStartDate']").click()
    page.locator("//input[@name='medicationStartDate']").fill("01-25-2025")
    page.locator("(//input[@placeholder='Choose Date'])[2]").click()
    page.locator("(//input[@placeholder='Choose Date'])[2]").fill("12-23-2025")
    page.get_by_placeholder("Select Provider").click()
    page.get_by_placeholder("Select Provider").fill(local_data.provider2)
    page.get_by_role("option", name=local_data.provider2).click()
    page.get_by_placeholder("Type here").click()
    page.get_by_placeholder("Type here").fill(medication["medication_note2"])
    page.get_by_role("button", name="Save").click()
    page.get_by_text("Medication updated successfully").click()
    page.get_by_role("tab", name="Active Medications").click()
    
    page.get_by_text(medication["medicine2"], exact=True).click()
    page.get_by_label("Take 310 Drops Bedtime by Optic Route Twice A Day").click()
    page.get_by_text("01/25/2025").click()
    page.get_by_text("12/23/2025").click()
    page.get_by_test_id("MoreVertIcon").click()
    
    # Delete
    page.get_by_role("menuitem", name="Delete").click()
    page.get_by_text("Are You Sure?").click()
    page.get_by_text("you want to delete this Active Medication").click()
    page.get_by_role("button", name="Yes,Sure").click()
    page.get_by_text("Medication archived successfully").click()
    print("Medication Module : PASS")