from playwright.sync_api import Page

from Automation.utils import creds, data, local_data

def order(page: Page) -> None:
    page.locator("//p[.='Order']").click()
    #Add Lab Order
    page.locator("//p[.='Add New Order']").click()
    page.get_by_role("button", name="Lab").click()
    page.locator("(//input[@class= 'MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall MuiInputBase-inputAdornedEnd MuiAutocomplete-input MuiAutocomplete-inputFocused css-b52kj1'])[1]").click()
    page.get_by_role("option", name="California").click()
    page.get_by_text("Locations").click()
    page.get_by_placeholder("Search And Select").first.click()
    page.get_by_role("option", name="Test Lab", exact=True).click()
    page.get_by_text("Locations").click()
    page.get_by_placeholder("Search And Select").first.click()
    page.get_by_role("option", name="330440-7", exact=True).click()
    page.get_by_text("Locations").click()
    page.get_by_placeholder("Search And Select").first.click()
    page.get_by_role("option", name="85131", exact= True).click()
    page.get_by_text("Icd Code").click()
    page.get_by_placeholder("Patient Instructions").fill("Patient instruction test")
    page.get_by_placeholder("Lab instructions to test center").fill("Lab Instructions To Test Center test")
    page.get_by_test_id("CalendarIcon").click()
    page.get_by_test_id("ClockIcon").click()
    page.get_by_role("option", name="12").click()
    page.get_by_text("00", exact=True).click()
    page.get_by_role("option", name= "PM").click()
    page.get_by_role("button", name="Order").click()

    #Add Result(Lab)
    page.locator("//p[.='Result']").click()
    page.get_by_role("button", name="Add New Result").click()
    page.get_by_placeholder("Enter Lab Description").fill("Lab description test")
    page.get_by_placeholder("Select").first.click()
    page.get_by_text("here").first.click()
    page.get_by_placeholder("Enter Result Value").fill("100")
    page.get_by_test_id("CalendarIcon").click()
    page.get_by_role("gridcell", name=data.day).click()
    page.get_by_placeholder("Select").nth(1).click()
    #page.get_by_text("Above Upper Panic Limits", exact=True).click()
    page.get_by_placeholder("Enter Note").fill("Test note")
    file= page.query_selector('input[type="file"]')
    path = creds.order_data_pdf
    file.set_input_files(path)
    page.get_by_role("button",name="Save").click()


    #Delete Lab order
    page.locator("//p[.='Order']").nth(1).click()
    page.locator("(//div[text()='Lab']/following::div[@class='MuiBox-root css-gmuwbf'])[1]").click()
    page.get_by_role("menuitem", name="Delete").click()
    page.get_by_role("button", name="Yes,Sure").click()

    #Add Imaging Order
    page.locator("//p[.='Add New Order']").click()
    page.get_by_role("button", name="Imaging").click()
    page.locator("(//input[@class= 'MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall MuiInputBase-inputAdornedEnd MuiAutocomplete-input MuiAutocomplete-inputFocused css-b52kj1'])[1]").click()
    page.get_by_role("option", name="California").click()
    page.get_by_text("Locations").click()
    page.get_by_placeholder("Search Imaging Center For Order").click()
    page.get_by_role("option", name="Imaging Center - 12345", exact=True).click()
    page.wait_for_timeout(1000)
    page.get_by_placeholder("Search And Select").first.click()
    page.get_by_role("option", name="Test Lab", exact=True).click()
    page.get_by_text("Locations").click()
    page.get_by_placeholder("Search And Select").first.click()
    page.get_by_role("option", name="330440-7", exact=True).click()
    page.get_by_text("Locations").click()
    page.get_by_placeholder("Search And Select").first.click()
    page.get_by_role("option", name="85131", exact= True).click()
    page.get_by_text("Icd Code").click()
    page.get_by_placeholder("Patient Instructions").fill("Patient instruction test")
    page.get_by_placeholder("Lab instructions to test center").fill("Lab Instructions To Test Center test")
    page.get_by_test_id("CalendarIcon").click()
    page.get_by_test_id("ClockIcon").click()
    page.get_by_role("option", name="12").click()
    page.get_by_text("00", exact=True).click()
    page.get_by_role("option", name= "PM").click()
    page.get_by_placeholder("Search Provider").first.click()
    page.get_by_role("option", name=local_data.provider1).click()
    page.get_by_placeholder("Search Provider").first.click()
    page.get_by_role("option", name=local_data.provider2).click()
    page.get_by_role("button", name="Order").click()

    #Add Result (Imaging)
    page.locator("//p[.='Result']").click()
    page.get_by_role("button", name="Add New Result").click()
    page.get_by_placeholder("Enter Lab Description").fill("Lab description test")
    page.get_by_placeholder("Select").first.click()
    page.get_by_text("here").first.click()
    page.get_by_placeholder("Enter Result Value").fill("100")
    page.get_by_test_id("CalendarIcon").click()
    page.get_by_role("gridcell", name=data.day).click()
    page.get_by_placeholder("Select").nth(1).click()
    #page.get_by_text("Above Upper Panic Limits", exact=True).click()
    page.get_by_placeholder("Enter Note").fill("Test note")
    file= page.query_selector("input[type='file']")
    path = creds.order_data_pdf
    file.set_input_files(path)
    page.get_by_role("button",name="Save").click()

    #Delete Imaging order
    page.locator("//p[.='Order']").nth(1).click()
    page.locator("(//div[text()='Imaging']/following::div[@class='MuiBox-root css-gmuwbf'])[1]").click()
    page.get_by_role("menuitem", name="Delete").click()
    page.get_by_role("button", name="Yes,Sure").click()

    # Prescription Order
def prescription_order(page: Page):
    page.get_by_role("tab", name="Order").click()
    page.get_by_role("tab", name="Prescription Order").click()
    page.get_by_role("button", name="Add Prescription").click()
    
    page.get_by_placeholder("Type").click()
    page.get_by_role("option", name="New Rx").click()
    page.get_by_placeholder("Select Or Search Medicine").click()
    page.get_by_role("option", name="Guanidine Hydrochloride").click()
    page.get_by_role("combobox", name="Select Provider").click()
    page.get_by_role("option", name=local_data.provider1).click()
    page.get_by_placeholder("Select", exact=True).click()
    page.get_by_role("option", name="Silverside").click()
    page.locator("input[name=\"medicationStartDate\"]").fill("03-20-2025")
    
    page.locator("input[name=\"directionToPatient\"]").fill("Take one tablet daily with water")
    page.locator("input[name=\"duration\"]").fill("30 days")
    page.locator("input[name=\"quantity\"]").fill("30")
    page.get_by_placeholder("unit").click()
    page.get_by_role("option", name="Tablet").click()
    page.get_by_placeholder("Refill").fill("2")
    page.get_by_placeholder("Choose Date").nth(1).fill("03-25-2025")
    page.get_by_placeholder("Choose Date").nth(2).fill("04-25-2025")
    
    page.get_by_placeholder("Search and Select Pharmacy").click() 
    page.get_by_role("option", name="Test Pharmacy 1").click()
    page.get_by_role("textbox", name="Select Date").fill("03-26-2025")
    # page.get_by_role("combobox", name="Select Date").fill()
    page.locator("input[name=\"priorAuthorization\"]").fill("Approved")
    page.get_by_role("textbox", name="Select Provider").fill("Ensure patient counseling on potential side effects")
    page.get_by_placeholder("Search and Select Code").click()
    page.get_by_role("option", name="E11.9").click()
    
    page.get_by_role("button", name="Save as Rx Template").click()
    page.get_by_text("Prescription form created successfully.").click()
    page.wait_for_timeout(1000)