from playwright.sync_api import Page
from Automation.utils import creds, local_data

def vaccine(page: Page, vaccine: dict):
# VACCINES
    page.get_by_role("tab", name="Vaccines").click()
    # Add Vaccine
    page.get_by_role("button", name="Add Vaccine").click()
    page.get_by_placeholder("Select Or Search Vaccine").click()
    page.get_by_role("option", name=vaccine["vaccine1"]).click()
    page.locator("(//input[@placeholder='Choose Date'])[1]").click()
    page.locator("(//input[@placeholder='Choose Date'])[1]").fill("01-30-2025")
    page.get_by_placeholder("Administer By").click()
    page.get_by_placeholder("Administer By").fill(local_data.provider1)
    page.get_by_role("option", name=local_data.provider1).click()
    page.locator("(//input[@placeholder='Choose Date'])[2]").click()
    page.locator("(//input[@placeholder='Choose Date'])[2]").fill("12-25-2025")
    page.get_by_placeholder("Enter Amount").fill("0.5")
    page.get_by_placeholder("Unit").click()
    page.get_by_role("option", name="Mg", exact=True).click()
    page.get_by_placeholder("Route").click()
    page.get_by_role("option", name="Injection").click()
    page.get_by_placeholder("Site").click()
    page.get_by_role("option", name="ArmLeftUpper").click()
    page.get_by_placeholder("Enter Manufacturer").fill("Bharat Biotech")
    page.get_by_placeholder("Enter Lot").fill("PZ123456")
    page.get_by_role("button", name="Save").click()
    page.get_by_text("Vaccine created successfully").click()
    
    page.get_by_role("cell", name=vaccine["vaccine1"]).click(click_count=3)
    page.get_by_role("cell", name="01/30/2025").click()
    page.get_by_role("cell", name=local_data.provider1).click()
    page.get_by_role("cell", name="12/25/2025").click()
    page.get_by_role("cell", name="0.5", exact=True).click()
    page.get_by_role("cell", name="Injection").click()
    page.get_by_role("cell", name="ArmLeftUpper").click()
    page.get_by_role("cell", name="Bharat Biotech").click()
    page.get_by_role("cell", name="PZ123456").click()
    page.get_by_test_id("MoreVertIcon").click()
    # print("Vaccine created successfully")
    
    # Edit
    page.get_by_role("menuitem", name="Edit").click()
    page.get_by_placeholder("Select Or Search Vaccine").click()
    page.get_by_role("option", name=vaccine["vaccine2"]).click()
    page.locator("(//input[@placeholder='Choose Date'])[1]").click()
    page.locator("(//input[@placeholder='Choose Date'])[1]").fill("02-20-2025")
    page.get_by_placeholder("Administer By").click()
    page.get_by_placeholder("Administer By").fill(local_data.provider2)
    page.get_by_role("option", name=local_data.provider2).click()
    page.locator("(//input[@placeholder='Choose Date'])[2]").click()
    page.locator("(//input[@placeholder='Choose Date'])[2]").fill("11-23-2025")
    page.get_by_placeholder("Enter Amount").fill("1")
    page.get_by_placeholder("Unit").click()
    page.get_by_role("option", name="Mg", exact=True).click()
    page.get_by_placeholder("Route").click()
    page.get_by_role("option", name="Dental").click()
    page.get_by_placeholder("Site").click()
    page.get_by_role("option", name="Bladder").click()
    page.get_by_placeholder("Enter Manufacturer").fill("Pfizer-BioNTech")
    page.get_by_placeholder("Enter Lot").fill("FL456789")
    page.get_by_role("button", name="Save").click()
    page.get_by_text("Vaccine updated successfully").click()

    page.get_by_role("cell", name=vaccine["vaccine2"]).click(click_count=3)
    page.get_by_role("cell", name="02/20/2025").click()
    page.get_by_role("cell", name=local_data.provider2).click()
    page.get_by_role("cell", name="11/23/2025").click()
    page.get_by_role("cell", name="1", exact=True).click()
    page.get_by_role("cell", name="Dental").click()
    page.get_by_role("cell", name="Bladder").click()
    page.get_by_role("cell", name="Pfizer-BioNTech").click()
    page.get_by_role("cell", name="FL456789").click()
    # print("Vaccine updated successfully")
    
    # Delete
    page.get_by_test_id("MoreVertIcon").click()
    page.get_by_role("menuitem", name="Delete").click()
    page.get_by_text("Are You Sure?").click()
    page.get_by_text("you want to delete this Vaccine").click()
    page.get_by_role("button", name="Yes,Sure").click()
    page.get_by_text("Vaccine archived successfully").click()
    # print("Vaccine archived successfully")
    print("Vaccine Module : PASS")